import Head from 'next/head';


export default function Home() {
    return (
        <div className="h-screen flex items-center justify-center bg-zinc-900">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="max-w-xl bg-white rounded-lg p-8 bg-zinc-800 shadow-lg">
                <h1 className="text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-br from-pink-700 to-red-600">
                    United Computations.
                </h1>
            </main>
        </div>
    )
}
